branches:
  only:
  - master
  - /^release/.*$/
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
jobs:
  include:
    - name: setup
      script:
      - echo $signing_secret_key | base64 --decode | gpg --import
      - echo $signing_ownertrust | base64 --decode | gpg --import-ownertrust
      - cp .ci.settings.xml $HOME/.m2/settings.xml
    - name: build
      script: mvn --no-transfer-progress -Prelease-commons,sonatype-oss-release clean package site
    - name: deploy
      if: (NOT type IN (pull_request)) AND (branch = master)
      script:
      - mvn --no-transfer-progress -Prelease-commons,sonatype-oss-release deploy site site:stage scm-publish:publish-scm
      - mvn -Ptravis coveralls:report && mvn --no-transfer-progress -Prelease-commons,github deploy
