language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_install:
- echo $signing_secret_key | base64 --decode | gpg --import
- echo $signing_ownertrust | base64 --decode | gpg --import-ownertrust
install: echo "Skipping pre-fetch of maven dependencies"
script: cp .ci.settings.xml $HOME/.m2/settings.xml && mvn --no-transfer-progress -Prelease-commons,sonatype-oss-release clean deploy site site:stage scm-publish:publish-scm
after_success: mvn -Ptravis coveralls:report && mvn --no-transfer-progress -Prelease-commons,github deploy && mvn deploy -Dregistry=https://maven.pkg.github.com/funfried -Dtoken=$github_token
