language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: echo "Skipping pre-fetch of maven dependencies"
script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -Prelease-commons,sonatype-oss-release clean deploy site site:stage scm-publish:publish-scm -Dgithub_username=$github_username -Dgithub_token=$github_token -Dsigning_keypass=$signing_keypass -Dsonatype_password=$sonatype_password -Dsonatype_username=$sonatype_username
