branches:
  only:
  - master
  - /^release/.*$/
dist: focal
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - apt-get update
  - apt-get install -y maven
before_script:
  - if [[ $SHIPPABLE_JDK_VERSION == "oraclejdk8" ]] ; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; export PATH="$PATH:/usr/lib/jvm/java-8-oracle/bin"; export java_path="/usr/lib/jvm/java-8-oracle/jre/bin/java"; fi
  - update-alternatives --set java $java_path
  - java -version
jobs:
  include:
    - name: build
      if: (type IN (pull_request)) OR (branch != master)
      before_script:
      - cp .ci.settings.xml $HOME/.m2/settings.xml
      script: mvn --no-transfer-progress -Prelease-commons,sonatype-oss-release package site
    - name: build and deploy
      if: (NOT type IN (pull_request)) AND (branch = master)
      before_script:
      - export MAVEN_OPTS="-Xms128m -Xmx512m --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
      - export GPG_TTY=$(tty)
      - echo $signing_secret_key | base64 --decode | gpg --batch --import
      - echo $signing_ownertrust | base64 --decode | gpg --import-ownertrust
      - cp .ci.settings.xml $HOME/.m2/settings.xml
      script:
      - mvn --no-transfer-progress -Prelease-commons,sonatype-oss-release deploy site site:stage scm-publish:publish-scm
      - mvn -Ptravis coveralls:report
      - mvn --no-transfer-progress -Prelease-commons,github clean deploy
      after_success:
      - bash <(curl -s https://codecov.io/bash)
