version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11
branches:
  only:
    - master
    - /^release/.*$/
  except:
    - gh-pages
os: Windows Server 2019
image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('https://downloads.apache.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.8.2\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-Xms128m -Xmx512m
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - cp .ci.settings.xml C:\maven\apache-maven-3.8.2\conf\settings.xml && mvn --no-transfer-progress -Denv.github_username=%github_username% -Denv.github_token=%github_token% clean package site
