# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build and Deploy with Maven
      run: |
        echo ${{ secrets.GPG_SIGNING_SECRET_KEY }} | base64 --decode | gpg --batch --import
        echo ${{ secrets.GPG_SIGNING_OWNERTRUST }} | base64 --decode | gpg --import-ownertrust
        mvn -s .ci.settings.xml --no-transfer-progress -Dgh_username=${{ secrets.GH_USERNAME }} -Dgh_token=${{ secrets.GH_TOKEN }} -Prelease-commons,sonatype-oss-release deploy site site:stage scm-publish:publish-scm
        mvn -s .ci.settings.xml -Dgh_username=${{ secrets.GH_USERNAME }} -Dgh_token=${{ secrets.GH_TOKEN }} -Ptravis coveralls:report
        mvn -s .ci.settings.xml --no-transfer-progress -Dgh_username=${{ secrets.GH_USERNAME }} -Dgh_token=${{ secrets.GH_TOKEN }} -Prelease-commons,github clean deploy
        bash <(curl -s https://codecov.io/bash)
      env:
        MAVEN_OPTS: -Xms128m -Xmx512m --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
        GPG_TTY: $(tty)
